#REFAÇA O DESAFIO 009, MOSTRANDO A TABUADA DE NÚMERO QUE O USUÁRIO ESCOLHER, SÓ QUE AGORA UTILIZANDO UM LAÇO FOR.

c = 0 #contador
t = int(input('Digite a tabuada que deseja ver: ')) #Seleção do dividendo
print('=' * 5, f'TABUADA DO {t}', '=' * 5) #visual
for c in range(0, 10):#Laçp
    c += 1#contador
    cal = t * c#calculo
    print(f'{c} x {t} = {cal}')#Saida

#CORRIGIDO
    
#RESLUÇÂO
    
'''

'''